name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with const fn features
      run: cargo build --verbose
    - name: Build with non const fn features
      run: cargo build --no-default-features --features "non_constant_sizeof" --verbose
    - name: Run tests with const fn features
      run: cargo test --verbose
    - name: Run tests with non const fn features
      run: cargo test --no-default-features --features "non_constant_sizeof" --verbose
